# Generated by Django 4.2.7 on 2023-11-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passcode',
            field=models.SmallIntegerField(blank=True, max_length=4, null=True, verbose_name='Passcode'),
        ),
    ]
