# Generated by Django 4.2.7 on 2023-11-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_managers_user_date_joined_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passcode',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Passcode'),
        ),
    ]
