# Generated by Django 4.2.7 on 2023-11-10 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_invited_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='invited_by',
            new_name='invited_users',
        ),
    ]
