# Generated by Django 4.2.7 on 2023-11-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_invited_by_user_invited_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invited_users',
        ),
        migrations.AddField(
            model_name='user',
            name='invited',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Invite_code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Users_invite_code'),
        ),
    ]
