# Generated by Django 4.2.7 on 2023-11-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_invited_users_user_invited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_invited',
            field=models.BooleanField(default=False, verbose_name='Is_user_invited'),
        ),
    ]
