version: '3.11'
services:

  db:
    image: postgres:14.8-alpine
    container_name: db
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata

  app:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    container_name: app
    ports:
      - '8002:8002'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env